export default {
    IceResourceScopes: {
        IceResource: "ICE",
        AIScope: "AI",
        PSIScope: "PSI",
        WMSScope: "WMS",
    },
    IceRoleTypes: {
        Guest: "GUEST",
        Admin: "ADMIN",
        Host: "HOST",
    },

    // OMS采购单状态
    OMSPurchaseOrderStatus: {
        /// <summary>
        /// 待审核
        /// </summary>
        PendingReview: 101,
        /// <summary>
        /// 采购中
        /// </summary>
        Purchasing: 102,
        /// <summary>
        /// 已完成
        /// </summary>
        Completed: 103,
        /// <summary>
        /// 作废
        /// </summary>
        Invalid: 999
    },
    // OMS 退货单状态
    OMSPurchaseReturnOrderStatus: {
        /// <summary>
        /// 待审核
        /// </summary>
        PendingReview: 101,
        /// <summary>
        /// 退货中
        /// </summary>
        Returning: 102,
        /// <summary>
        /// 已完成
        /// </summary>
        Completed: 103,
        /// <summary>
        /// 作废
        /// </summary>
        Invalid: 999
    },
    // OMS 外部订单来源
    OMSOuterOrderSource: {
        /// <summary>
        /// 淘宝
        /// </summary>
        TAOBAO: "TAOBAO",
        /// <summary>
        /// 京东
        /// </summary>
        JINGDONG: "JINGDONG",
        /// <summary>
        /// 抖店
        /// </summary>
        TOUTIAO: "TOUTIAO",
        /// <summary>
        /// 快手
        /// </summary>
        KUAISHOU: "KUAISHOU",
        /// <summary>
        /// 阿里1688
        /// </summary>
        ALI1688: "ALI1688",
        /// <summary>
        /// 快团团
        /// </summary>
        KUAITUANTUAN: "KUAITUANTUAN",
        /// <summary>
        /// 唯品会
        /// </summary>
        WEIPINHUI: "WEIPINHUI",
        /// <summary>
        /// 有赞
        /// </summary>
        YOUZAN: "YOUZAN",
        /// <summary>
        /// 拼刀刀
        /// </summary>
        PINDUODUO: "PINDUODUO",
        /// <summary>
        /// 其他
        /// </summary>
        OTHER: "OTHER",
    },
    OMSOutboundOrderStatus: {
        /// <summary>
        /// 待审核
        /// </summary>
        PendingReview: "PendingReview",
        /// <summary>
        /// 作业中
        /// </summary>
        Working: "Working",
        /// <summary>
        /// 已出库
        /// </summary>
        OutStocked: "OutStocked",
        /// <summary>
        /// 作废
        /// </summary>
        Invalid: "Invalid",
    },
    // 门店补货单状态
    STSaleOrderStatus: {
        /// <summary>
        /// 待确认
        /// </summary>
        WaitConfirm: "WaitConfirm",
        /// <summary>
        /// 待处理
        /// </summary>
        ToBeProcessed: "ToBeProcessed",
        /// <summary>
        /// 处理中
        /// </summary>
        Processing: "Processing",
        /// <summary>
        /// 已收货
        /// </summary>
        Completed: "Completed",
        /// <summary>
        /// 驳回
        /// </summary>
        Rejected: "Rejected",
    },
    // 门店补货单退货状态
    STSaleOrderReturnStatus: {
        /// <summary>
        /// 待确认
        /// </summary>
        WaitConfirm: "WaitConfirm",
        /// <summary>
        /// 待处理
        /// </summary>
        ToBeProcessed: "ToBeProcessed",
        /// <summary>
        /// 退货中
        /// </summary>
        Returning: "Returning",
        /// <summary>
        /// 已完成
        /// </summary>
        Completed: "Completed",
        /// <summary>
        /// 驳回
        /// </summary>
        Rejected: "Rejected",
    },

    // 入库单类型
    InboundOrderType: {
        /// <summary>
        /// 采购
        /// </summary>
        Purchase: 101,
        /// <summary>
        /// 退货
        /// </summary>
        SaleReturn: 102,
        /// <summary>
        /// 调拨
        /// </summary>
        Transfer: 103,
        /// <summary>
        /// 自定义
        /// </summary>
        Customize: 999,
    },
    // 入库单状态
    InboundOrderStatus: {
        /// <summary>
        /// 待收货
        /// </summary>
        PendingReceipt: 101,
        /// <summary>
        /// 验货中
        /// </summary>
        UnderInspection: 102,
        /// <summary>
        /// 上架中
        /// </summary>
        OnTheShelf: 103,
        /// <summary>
        /// 已上架
        /// </summary>
        Shelfed: 104,
        /// <summary>
        /// 作废
        /// </summary>
        Invalid: 999
    },
    // 出库单状态
    OutboundOrderStatus: {
        /// <summary>
        /// 待拣货
        /// </summary>
        ToBePicked: 101,
        /// <summary>
        /// 拣货中
        /// </summary>
        Picking: 102,
        /// <summary>
        /// 待出库
        /// </summary>
        TobeOut: 104,
        /// <summary>
        /// 已出库
        /// </summary>
        Outofstock: 105,
        /// <summary>
        /// 作废
        /// </summary>
        Invalid: 999
    },
    // 拣货单状态
    PickListStatus: {
        /// <summary>
        /// 拣货中
        /// </summary>
        Picking: 102,
        /// <summary>
        /// 已完成
        /// </summary>
        Complete: 104,
        /// <summary>
        /// 作废
        /// </summary>
        Invalid: 999
    },
    OutboundOrderType: {
        /// <summary>
        /// 调拨
        /// </summary>
        Transfer: 'Transfer',
        /// <summary>
        /// 门店订单
        /// </summary>
        Sale: "Sale",
        /// <summary>
        /// 采购退货
        /// </summary>
        PurchaseReturn: "PurchaseReturn",
        /// <summary>
        /// 其他
        /// </summary>
        Customize: "Customize",
    },
    // 盘点任务状态
    WarehouseCheckStatus: {
        /// <summary>
        /// 待盘点
        /// </summary>
        Waiting: 101,
        /// <summary>
        /// 盘点中
        /// </summary>
        Checking: 102,
        /// <summary>
        /// 已盘点
        /// </summary>
        Checked: 103,
        /// <summary>
        /// 作废
        /// </summary>
        Invalid: 999
    },
    // 订单变更类型
    OrderChangeLogType: {
        /// <summary>
        /// 入库单
        /// </summary>
        InboundOrder: 101,
        /// <summary>
        /// 出库单
        /// </summary>
        OutboundOrder: 102,
    },
    // 报损单状态
    LossReportOrderStatus: {
        /// <summary>
        /// 待处理
        /// </summary>
        ToBeProcessed: 101,
        /// <summary>
        /// 已处理
        /// </summary>
        Processed: 102,
        /// <summary>
        /// 作废
        /// </summary>
        Invalid: 999
    },
    ClientIntentionType: {
        // 无意向
        NO: "NO",
        // 未知
        UNKNOWN: "UNKNOWN",
        // 有意向
        HAVE: "HAVE",
        // 已使用
        USED: "USED",
    }
}